### ISSUE TITLE
[Question] Can I use this for a skid steer robot (4 motors)?

### ISSUE THREAD

**Issue by jorgemiar** [johnkok/ros_odrive#1]
I have a skid steer robot using two odrives for 4 BLDC motors. Is there a way I could use this package to drive my 4 motors?Basically the two motors on one odrive are meant to spin at the same speed and the same on the other side of the robot.

**Comment by johnkok** [comment]
Normally you can initiate two separate instances for controlling the four motors. 
Even if two motors are running with the same speed, I suppose that you will need separate controller and drivers - one for each motor - since the force and traction will be different on each wheel.

**Comment by jorgemiar** [comment]
So I would have to run the node twice, each one talking to an odrive board right? 

Yes, each motor will need its own controller (to deal with slip etc), but technically the drive signal (Twist message) being sent to the wheels on each side of the robot should be the same.

**Comment by johnkok** [comment]
Yes you can start two nodes by passing the serial number of each board in the parameters.
