### ISSUE TITLE
[Question] What are the units of fval? Can I send commands to both motors at the same time?

### ISSUE THREAD

**Issue by jorgemiar** [johnkok/ros_odrive#2]
Are the units of _fval_ [count/s]? And is this the same for the _vel_ being published?

Also, is it possible to send a velocity command to both motors at the same time? As the control message only sends 1 axis at a time.

**Comment by johnkok** [comment]
For Velocity control, the fval unit is "encounter counts/second" as it is defined by the target. 
Currently, setting velocity on both axis using a single command is not supported, but this can be easily achieved by extending the existing commands and adding a new command (I will also added to my backlog...). Of course you may have a small delay between transferring the data to target for each channel through USB- but for most applications this is not a problem.
